#!/usr/bin/env python3
# Verify GLEP63 compliance of OpenPGP keys (using GnuPG).
# (c) 2018 Michał Górny
# Released under the terms of 2-clause BSD license.

import argparse
import collections
import datetime
import email.utils
import functools
import io
import subprocess
import sys


key_keys = ('validity', 'key_length', 'key_algo', 'keyid',
            'creation_date', 'expiration_date', 'key_caps',
            'curve')

# tuples for "gpg --with-colons" output
Key = collections.namedtuple('Key', key_keys)
PublicKey = collections.namedtuple('PublicKey',
    key_keys + ('subkeys', 'uids'))
UID = collections.namedtuple('UID',
    ('validity', 'creation_date', 'expiration_date', 'uid_hash',
     'user_id'))


def process_date(d):
    if d == '':
        return None
    elif 'T' in d:
        return datetime.datetime.strptime(d, '%Y%m%dT%H%M%S')
    else:
        return datetime.datetime.utcfromtimestamp(int(d))


def process_initial_key_fields(validity, key_length, key_algo, keyid,
        creation_date, expiration_date):
    return (
        validity,
        int(key_length),
        int(key_algo),
        keyid,
        process_date(creation_date),
        process_date(expiration_date),
    )


# gpg/openpgp consts
class Validity(object):
    INVALID = 'i'
    REVOKED = 'r'
    EXPIRED = 'e'


class KeyAlgo(object):
    RSA                 = 1
    RSA_ENCRYPT_ONLY    = 2
    RSA_SIGN_ONLY       = 3
    ELGAMAL             = 16
    DSA                 = 17
    ECDH                = 18
    ECDSA               = 19
    EDDSA               = 22


KeyIssue = collections.namedtuple('KeyIssue',
    ('key', 'machine_desc', 'long_desc'))
KeyWarning = collections.namedtuple('KeyWarning',
    ('key', 'machine_desc', 'long_desc'))


SubKeyIssue = collections.namedtuple('SubKeyIssue',
    ('key', 'subkey', 'machine_desc', 'long_desc'))
SubKeyWarning = collections.namedtuple('SubKeyWarning',
    ('key', 'subkey', 'machine_desc', 'long_desc'))


UIDIssue = collections.namedtuple('UIDIssue',
    ('key', 'uid', 'machine_desc', 'long_desc'))


IssueClasses = collections.namedtuple('IssueClasses',
    ('key', 'subkey', 'uid'))


FAIL = IssueClasses(KeyIssue, SubKeyIssue, UIDIssue)
WARN = IssueClasses(KeyWarning, SubKeyWarning, None)


class Years(object):
    def __init__(self, val):
        self.years = val

    @property
    def days(self):
        return self.years * 365.24

    def __str__(self):
        return '{} years'.format(self.years)


class Days(object):
    def __init__(self, val):
        self.days = val

    def __str__(self):
        return '{} days'.format(self.days)


GLEP63_1_RSA2048 = {
    '__doc__': 'GLEP 63 v1 without RSA4096 preference',
    # DSA key algorithm
    'algo:dsa': WARN,
    'algo:dsa:minlength': 2048,
    # RSA key algorithm
    'algo:rsa:minlength': 2048,
    # EC25519 algorithm
    'algo:ec25519': FAIL,
    # other algorithms
    'algo:invalid': FAIL,
    # expiration max values (fatal)
    'expire:max:key': Years(5),
    'expire:max:subkey': Years(5),
    # expiration recommended values (warning)
    'expire:recommended:key': Years(3),
    'expire:recommended:subkey': Years(1),
    # renewal
    'expire:short': WARN,
    'expire:short:length': Days(14),
    # multipurpose subkeys
    'subkey:multipurpose': WARN,
    # lack of signing subkey
    'subkey:none': FAIL,
    # lack of @gentoo.org UID
    'uid:nogentoo': WARN,
}

GLEP63_1_STRICT = GLEP63_1_RSA2048.copy()
GLEP63_1_STRICT.update({
    '__doc__': 'GLEP 63 v1 with RSA4096 preference',
    # RSA key algorithm
    'algo:rsa:recommended': 4096,
})

GLEP63_1_RSA2048_EC25519 = GLEP63_1_RSA2048.copy()
GLEP63_1_RSA2048_EC25519.update({
    '__doc__': 'GLEP 63 v1 with RSA2048 preference and allowed EC25519',
    # EC25519 algorithm
    'algo:ec25519': None,
})

GLEP63_2_DRAFT_20180707 = {
    '__doc__': 'GLEP 63 v2 draft as of 2018-07-07',
    # DSA key algorithm
    'algo:dsa': FAIL,
    # RSA key algorithm
    'algo:rsa:minlength': 2048,
    # EC25519 algorithm
    'algo:ec25519': None,
    # other algorithms
    'algo:invalid': FAIL,
    # expiration max values (fatal)
    'expire:max:key': Days(900),
    'expire:max:subkey': Days(900),
    # renewal
    'expire:short': FAIL,
    'expire:short:length': Days(14),
    # multipurpose subkeys
    'subkey:multipurpose': WARN,
    # lack of signing subkey
    'subkey:none': FAIL,
    # lack of @gentoo.org UID
    'uid:nogentoo': WARN,
}

SPECS = {
    'glep63-1-rsa2048': GLEP63_1_RSA2048,
    'glep63-1-strict': GLEP63_1_STRICT,
    'glep63-1-rsa2048-ec25519': GLEP63_1_RSA2048_EC25519,
    'glep63-2-draft-20180707': GLEP63_2_DRAFT_20180707,
}

DEFAULT_SPEC = 'glep63-1-rsa2048'


def process_gnupg_colons(f):
    """
    Process "gpg --with-colons" output from stream @f, and into list
    of key objects.
    """

    keys = []

    for l in f:
        vals = l.split(':')

        # type of record
        if vals[0] == 'pub':
            keys.append(PublicKey(
                *process_initial_key_fields(*vals[1:7]) +
                (vals[11], vals[16], [], [])))
        elif vals[0] == 'sub':
            assert keys
            keys[-1].subkeys.append(Key(
                *(process_initial_key_fields(*vals[1:7]) +
                (vals[11], vals[16]))))
        elif vals[0] == 'uid':
            assert keys
            keys[-1].uids.append(UID(vals[1], process_date(vals[5]),
                process_date(vals[6]), vals[7], vals[9]))

    return keys


def check_subkey(k, spec, key_type, issue_params):
    out = []

    issue_cls = functools.partial(getattr(FAIL, key_type), *issue_params)
    warning_cls = functools.partial(getattr(WARN, key_type), *issue_params)

    # 1. key algo/length
    if k.key_algo in (KeyAlgo.RSA_SIGN_ONLY, KeyAlgo.RSA_ENCRYPT_ONLY):
        out.append(warning_cls('algo:rsa:deprecated_only',
            'Sign-only/encrypt-only RSA keys are deprecated'))
        # set to common value for simplicity
        k.key_algo = KeyAlgo.RSA

    if k.key_algo in (KeyAlgo.DSA, KeyAlgo.ELGAMAL):
        dsa_key = spec.get('algo:dsa')
        if dsa_key == FAIL:
            out.append(issue_cls('algo:dsa',
                'DSA keys are disallowed (RSA is recommended)'))
        elif k.key_length < spec.get('algo:dsa:minlength', 0):
            out.append(issue_cls('algo:dsa:tooshort',
                'DSA key too short (has {} bits, should be {} bits)'
                .format(k.key_length, spec['algo:dsa:minlength'])))
        elif dsa_key == WARN:
            out.append(warning_cls('algo:dsa:discouraged',
                'DSA keys are discouraged (RSA is recommended)'))
    elif k.key_algo == KeyAlgo.RSA:
        rsa_key = spec.get('algo:rsa')
        # we currently don't have to implement forbidding RSA ;-)
        assert not rsa_key
        if k.key_length < spec.get('algo:rsa:minlength', 0):
            out.append(issue_cls('algo:rsa:tooshort',
                'RSA key too short (has {} bits, should be at least {} bits)'
                .format(k.key_length, spec['algo:rsa:minlength'])))
        elif k.key_length < spec.get('algo:rsa:recommended', 0):
            out.append(warning_cls('algo:rsa:short',
                'RSA key short (has {} bits, {} bits recommended)'
                .format(k.key_length, spec['algo:rsa:recommended'])))
    elif k.key_algo in (KeyAlgo.ECDH, KeyAlgo.ECDSA, KeyAlgo.EDDSA):
        ecc_key = spec.get('algo:ec25519')
        if ecc_key == FAIL:
            out.append(issue_cls('algo:ec25519',
                'ECC keys are disallowed (RSA is recommended)'))
        else:
            # warnings are not used at the moment
            assert ecc_key is None

            if k.curve not in ('ec25519', 'ed25519'):
                out.append(issue_cls('algo:ecc:invalid',
                    'ECC curve {} disallowed (only Curve 25519 supported)'
                    .format(k.curve)))

    elif spec.get('algo:invalid'):
        cls = issue_cls if spec['algo:invalid'] == FAIL else warning_cls
        out.append(issue_cls('algo:invalid',
            'Unexpected key algorithm'))

    # 2. key expiration
    expire_max = spec.get('expire:max:{}'.format(key_type))
    expire_recommended = spec.get('expire:recommended:{}'.format(key_type))
    if expire_max is not None or expire_recommended is not None:
        if expire_recommended is not None:
            expire_str = ('<{} recommended, {} max'
                    .format(expire_recommended, expire_max))
        else:
            expire_str = '{} max'.format(expire_max)

        if k.expiration_date is None:
            cls = issue_cls if expire_max is not None else warning_cls
            out.append(cls('expire:none',
                'No expiration date on public key ({})'.format(expire_str)))
        else:
            expire_left = k.expiration_date - datetime.datetime.utcnow()
            if expire_max is not None and expire_left.days > expire_max.days:
                out.append(issue_cls('expire:long',
                    'Expiration date is too long (is {}, {})'
                    .format(k.expiration_date, expire_str)))
            elif (expire_recommended is not None
                    and expire_left.days > expire_recommended.days):
                out.append(warning_cls('expire:long',
                    'Expiration date is long (is {}, {})'
                    .format(k.expiration_date, expire_str)))
            elif (spec.get('expire:short') is not None
                    and expire_left.days < spec['expire:short:length'].days):
                cls = issue_cls if spec['expire:short'] == FAIL else warning_cls
                out.append(cls('expire:short',
                    'Expiration date is short (is {}, less than {})'
                    .format(k.expiration_date, spec['expire:short:length'])))

    return out


def check_key(k, spec):
    out = []

    # 0. check key validity (only for whole key)
    if k.validity == Validity.INVALID:
        out.append(KeyIssue(k, 'validity:invalid',
            'Public key is invalid'))
        return out
    elif k.validity == Validity.REVOKED:
        out.append(KeyIssue(k, 'validity:revoked',
            'Public key has been revoked'))
        return out
    elif k.validity == Validity.EXPIRED:
        out.append(KeyIssue(k, 'validity:expired',
            'Public key has expired'))
        return out

    # 1. check public key
    out.extend(check_subkey(k, spec, 'key', (k,)))

    # 2. check subkeys
    # (sadly, we can't be sure *which* subkey is used for Gentoo,
    #  so we complain about all of them)
    has_signing_subkey = False
    for sk in k.subkeys:
        # check only signing subkeys
        if 's' not in sk.key_caps:
            continue
        # complain about invalid subkeys
        if sk.validity == Validity.INVALID:
            out.append(SubKeyIssue(k, sk, 'validity:invalid',
                'Subkey is invalid'))
        # skip expired and revoked subkeys
        if sk.validity in (Validity.REVOKED, Validity.EXPIRED):
            continue

        if len(sk.key_caps) > 1 and spec.get('subkey:multipurpose'):
            out.append(spec['subkey:multipurpose'].subkey(k, sk, 'subkey:multipurpose',
                'Subkey has multiple capabilities enabled (has: [{}]; use dedicated subkeys!)'
                .format(sk.key_caps)))
        else:
            has_signing_subkey = True

        out.extend(check_subkey(sk, spec, 'subkey', (k, sk)))

    if not has_signing_subkey and spec.get('subkey:none'):
        out.append(spec['subkey:none'].key(k, 'subkey:none',
            'Having a dedicated signing subkey is required'))

    # 3. check UIDs
    # (require the @gentoo.org e-mail)
    has_gentoo_uid = False
    for u in k.uids:
        # complain about invalid UIDs
        if u.validity == Validity.INVALID:
            out.append(UIDIssue(k, u, 'validity:invalid',
                'UID is invalid'))
        # skip expired and revoked UIDs
        if u.validity in (Validity.REVOKED, Validity.EXPIRED):
            continue

        name, addr = email.utils.parseaddr(u.user_id)
        if addr.endswith('@gentoo.org'):
            has_gentoo_uid = True

    if not has_gentoo_uid and spec.get('uid:nogentoo'):
        out.append(spec['uid:nogentoo'].key(k, 'uid:nogentoo',
            '@gentoo.org e-mail not in key UIDs'))

    return out


def main():
    argp = argparse.ArgumentParser()
    act = argp.add_mutually_exclusive_group(required=True)
    act.add_argument('-a', '--all', action='store_true',
            help='Verify all public keys in the local keyring')
    act.add_argument('-G', '--gnupg',
            nargs='+', metavar='FILE', type=argparse.FileType('r', encoding='UTF-8'),
            help='Process "gpg --with-colons" output from FILE(s) ("-" for stdin)')
    act.add_argument('-k', '--key-id', nargs='+',
            help='Check local GnuPG keys matching specified query (IDs, names)')
    act.add_argument('-K', '--keyring', nargs='+',
            help='Check all keys in specified keyrings (gpg --keyring syntax)')

    argp.add_argument('-S', '--spec', choices=SPECS, default=DEFAULT_SPEC,
            help='Spec to verify against')
    argp.add_argument('-e', '--errors-only', action='store_true',
            help='Print only errors (skip warnings)')
    argp.add_argument('-m', '--machine-readable', action='store_true',
            help='Print only machine-readable data (skip human-readable desc)')
    argp.add_argument('-w', '--warnings-as-errors', action='store_true',
            help='Treat warnings as errors (return unsucessfully if any)')

    opts = argp.parse_args()

    keys = []

    if opts.key_id is not None or opts.all or opts.keyring is not None:
        cmd = ['gpg', '--with-colons', '--list-keys']
        if opts.keyring is not None:
            cmd += ['--no-default-keyring']
            for k in opts.keyring:
                cmd += ['--keyring', k]
        if opts.key_id is not None:
            cmd += opts.key_id
        s = subprocess.Popen(cmd,
                stdin=subprocess.PIPE,
                stdout=subprocess.PIPE)
        sout = io.TextIOWrapper(s.stdout, encoding='UTF-8')
        keys = process_gnupg_colons(sout)
        if s.wait() != 0:
            print('Warning: GnuPG exited unnecessfully!')
    elif opts.gnupg is not None:
        for f in opts.gnupg:
            keys.extend(process_gnupg_colons(f))

    out = []
    for k in keys:
        out.extend(check_key(k, SPECS[opts.spec]))

    ret = 0
    for i in out:
        keyid = i.key.keyid
        if hasattr(i, 'subkey'):
            keyid += ':' + i.subkey.keyid
        elif hasattr(i, 'uid'):
            keyid += ':[{}]'.format(i.uid.user_id)

        if type(i) in FAIL:
            ret |= 1
            cls = '[E]'
        else:
            assert type(i) in WARN
            cls = '[W]'
            if opts.errors_only:
                continue
            if opts.warnings_as_errors:
                ret |= 2

        if opts.machine_readable:
            msg = [keyid, i.machine_desc]
        else:
            # decorate with readable UID
            sorted_uids = sorted(i.key.uids,
                    key=lambda x: not '@gentoo.org' in x.user_id)
            uid = '[{}]'.format(sorted_uids[0].user_id)
            msg = [keyid, uid, cls, i.machine_desc, i.long_desc]

        print(' '.join(msg))

    return ret


if __name__ == '__main__':
    sys.exit(main())
