#!/usr/bin/env python3
# Verify GLEP63 compliance of OpenPGP keys (using GnuPG).
# (c) 2018 Michał Górny
# Released under the terms of 2-clause BSD license.

import sys

from glep63.cli import main


if __name__ == '__main__':
    sys.exit(main())
